### ISSUE TITLE
Set A Timer

### ISSUE THREAD

**Issue by TabrynP** [vcu-cmsc355-f17/android-app-mmat#8]
As someone who wants to keep track of how long things take, so that I can accurately gauge the amount of time I take doing things, I want to be able to set a timer on my alarm clock app.

Scenario 1: Given I am on the home screen, when I press the "timer" tab, I am taken the a screen with a timer.

Scenario 2: Given I am on the timer screen, when I press the hour hand on the analog clock, I can move the desired hours I want the timer to tick for.

Scenario 2: Given I am on the timer screen, when I press the minute hand on the analog clock, I can move the desired minutes I want the timer to tick for.

Scenario 3: Given I am on the timer screen, when I press the second hand on the analog clock, I can move the desired second I want on the timer to tick for.

Scenario 4: Given that my timer is ticking, when the timer runs down to zero (or 12/12/12 on the analog clock), a set alarm will go off.

**Comment by pointermc** [comment]
EDIT TO SCENARIOS: The Timer Tab is now implementing a timer without an analog clock interface, so Scenario 2, 3, and 4 are not currently applicable.

New Scenario 2: Given I am on the timer tab, when I use the seekbars to set the timer to go off in 0 hours, 0 minutes, and 5 seconds, and press the Start button, the TextView with text "Start a Timer" should change to say "Done!" when the countdown reaches 0 Hours 0 Minutes 0 Seconds

**Comment by pointermc** [comment]
Scenario 1 Has been left unchanged

**Comment by pointermc** [comment]
New Scenario 3 : Given I am on the timer tab, when I use the hours, minutes, and seconds seekbars to set the timer to 1 hour, 0 minutes, and 3 seconds, and click the "Start" button, the timer should start to tick down. After letting the timer tick for 5 seconds, click the "Cancel" button. The timer should be stopped, and the hours, minutes, and seconds remaining should all be reset to 0.
